name: PR
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.2'
      - name: Check version
        run: ./scripts/version.sh check
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Lint
        run: |
          poetry run black . --check
          poetry run flake8
          poetry run mypy .
      - name: Set up API server
        uses: opvious/api-server-action@v0.2.0
        with:
          license-key: ${{ secrets.OPVIOUS_LICENSE_KEY }}
      - name: Register specifications
        run: ./scripts/specifications.sh register
      - name: Test
        run: poetry run pytest
      - name: Show API logs
        if: failure()
        run: opvious api logs
