name: PR
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[aio,test]
      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
      - name: Test
        run: pytest
        env:
          OPVIOUS_TOKEN: ${{ secrets.OPVIOUS_TOKEN }}
          PYTHONPATH: src
